# Generated by Django 3.1.4 on 2020-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0003_donorlist_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorlist',
            old_name='last_donate_date',
            new_name='aadhar_num',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='hbsAg_hcv_hIV',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='names',
        ),
        migrations.AddField(
            model_name='donorlist',
            name='District',
            field=models.CharField(blank=True, choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], max_length=18, null=True),
        ),
    ]
