# Generated by Django 3.1.4 on 2020-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0004_auto_20201220_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='occupation',
        ),
        migrations.AddField(
            model_name='donorlist',
            name='Priority',
            field=models.CharField(blank=True, choices=[('1.Health Administrators ', '1.Health Administrators'), ('2.defense(police or military) ', '2.defense(police or military)'), ('3.sanitising staff', '3.sanitising staff'), ('4.Prioritized Staff', '4.Prioritized Staff'), ('5.Senior citizens', '5.Senior citizens'), ('6.other Citizens', '6.other citizens')], max_length=39, null=True),
        ),
    ]
